[package]
name = "ClipboardDesktopRust"
version = "0.1.0"
edition = "2024"

[dependencies]
#eframe = "0.33.0"
#image = "0.25.9"
#egui_extras = { version = "0.33.2", features = ["all_loaders"] }
#winit = "0.30.12"
slint = "1.14.1"

[build-dependencies]
slint-build = "1.14.1"